[package]
name = "hybrid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
bevy_egui = "0.20.1"
bevy_prototype_lyon = "0.8.0"
bevy_rapier2d = "0.21.0"
rand = "0.8.5"
